[package]
org = "ballerinax"
name = "twilio"
version = "2.0.0"
export = ["twilio", "twilio.listener"]
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["Communication/Phone & SMS", "Cost/Paid"]
icon = "icon.png"
license = ["Apache-2.0"]

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-0.99.9-SNAPSHOT.jar"
groupId = "org.ballerinalang.twilio"
artifactId = "java-wrapper"
version = "0.99.9-SNAPSHOT"
