[package]
distribution = "2201.0.0"
org = "ballerinax"
name = "twilio"
version = "2.2.0"
export = ["twilio", "twilio.listener"]
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-twilio"
keywords = ["Communication/Call & SMS", "Cost/Paid"]
icon = "icon.png"
license = ["Apache-2.0"]

[[platform.java11.dependency]]
path = "../java-wrapper/build/libs/java-wrapper-2.2.0.jar"
groupId = "org.ballerinalang.twilio"
artifactId = "java-wrapper"
version = "2.2.0"
