[[dependency]]
org = "ballerina"
name = "url"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "auth"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.0.0"

[[dependency]]
org = "ballerina"
name = "http"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "mime"
version = "2.0.0"

[[dependency]]
org = "ballerina"
name = "os"
version = "1.0.0"
