name: CI

on:
  push:
    branches:
      - '**'
  repository_dispatch:
    types:
      check_connector_for_breaking_changes

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 11
              uses: actions/setup-java@v1
              with:
                  java-version: 11
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              env:
                  packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
                  packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
                  JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
              run: |
                  ./gradlew build
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack ./twilio
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
            - name: Ballerina Tests
              uses: ballerina-platform/ballerina-action@nightly
              with:
                  args:
                      test --code-coverage ./twilio
              env:
                  JAVA_HOME: /usr/lib/jvm/default-jvm
                  ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
                  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
                  SAMPLE_FROM_MOBILE: ${{ secrets.SAMPLE_FROM_MOBILE }}
                  SAMPLE_TO_MOBILE: ${{ secrets.SAMPLE_TO_MOBILE }}
                  SAMPLE_MESSAGE: ${{ secrets.SAMPLE_MESSAGE }}
                  SAMPLE_TWIML_URL: ${{ secrets.SAMPLE_TWIML_URL }}
                  SAMPLE_WHATSAPP_SANDBOX: ${{ secrets.SAMPLE_WHATSAPP_SANDBOX }}
                  CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
                  PORT: ${{ secrets.PORT }} 
           
            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./twilio/target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"

            - name: Allert notifier on failure
              if: failure() && (github.event.action == 'check_connector_for_breaking_changes')
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                --header 'Accept: application/vnd.github.v3+json' \
                --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data-raw '{
                  "event_type": "notify-ballerinax-connector-build-failure",
                  "client_payload": {
                    "repoName": "module-ballerinax-twilio",
                    "workflow": "CI"
                  }
                }'
