name: Pull_Request

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args: pack ./twilio
              env:
                  ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
                  AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
                  SAMPLE_FROM_MOBILE: ${{ secrets.SAMPLE_FROM_MOBILE }}
                  SAMPLE_TO_MOBILE: ${{ secrets.SAMPLE_TO_MOBILE }}
                  SAMPLE_MESSAGE: ${{ secrets.SAMPLE_MESSAGE }}
                  SAMPLE_TWIML_URL: ${{ secrets.SAMPLE_TWIML_URL }}
                  SAMPLE_WHATSAPP_SANDBOX: ${{ secrets.SAMPLE_WHATSAPP_SANDBOX }}
                  CALLBACK_URL: ${{ secrets.CALLBACK_URL }}
                  PORT: ${{ secrets.PORT }} 